{% set name = "pixcdust" %}
{% set version = "0.1.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pixcdust-{{ version }}.tar.gz
  sha256: 75199f9811a198e46c2cb2590e857ea225da8f4ee8430a7568c58899934636b5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.26.4,<2.0.0
    - fiona >=1.9.5,<2.0.0
    - pandas >=2.2.0,<3.0.0
    - geopandas >=0.14.3,<0.15.0
    - h3-py >=3.7.6,<4.0.0
    - xarray >=2024.2.0,<2025.0.0
    - shapely >=2.0.3,<3.0.0
    - black >=24.2.0,<25.0.0
    - flake8 >=7.0.0,<8.0.0
    - click >=8.1.7,<9.0.0
    - zcollection >=2024.2.0,<2025.0.0
    - netcdf4 >=1.6.5,<2.0.0
    - tqdm >=4.66.4,<5.0.0
    - pyogrio >=0.8.0,<0.9.0
    - pyarrow >=16.1.0,<17.0.0
    - eodag >=2.12.1,<3.0.0
    - folium >=0.16.0,<0.17.0
    - branca >=0.7.2,<0.8.0
    - xvec >=0.3.0,<0.4.0


test:
  imports:
    - pixcdust
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/SWOT-community/PixCDust
  summary: 'Tools and converters to facilitate local studies based on SWOT-HR Level-2 Pixel Cloud products.'
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - gbfree
